### ISSUE TITLE
Invalid Invite

### ISSUE THREAD

**Issue by chiquicalris-dev** [Votyn/SpaceBoat#14]
The invite found in the `README.md` file is invalid, this invite redirects you to discord.com and therefore Discord gives a 404 error.

**Comment by DeltaCoderr** [comment]
The last update was made in 2019, So we can't say anything if the server exists or not.

**Comment by XT3RM1N8R** [comment]
It just needs to be corrected to either of these:  
- https://discord.gg/spaceengine
- https://discord.com/invite/spaceengine
